name: maplibre_gl_example
description: Demonstrates how to use the maplibre_gl plugin.
publish_to: 'none'
version: 1.0.0+1
repository: https://github.com/maplibre/flutter-maplibre-gl
issue_tracker: https://github.com/maplibre/flutter-maplibre-gl/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter

  maplibre_gl_platform_interface:
    git:
      url: https://github.com/maplibre/flutter-maplibre-gl.git
      path: maplibre_gl_platform_interface
      ref: git-release-0.17.0

  maplibre_gl:
    git:
      url: https://github.com/maplibre/flutter-maplibre-gl.git
      ref: git-release-0.17.0

  location: ^5.0.3
  path_provider: ^2.0.15
  http: ^1.1.0
  collection: ^1.17.1
  # temporary fix:
  platform: ^3.1.0
  device_info_plus: ^9.0.2

# The following lines can be useful if you make changes to this plugin (specifically to the two sub-plugins), 
# e.g. because you contribute to the project.
# If the following lines are not commented out, your local versions of the sub-plugins will be used,
#  instead of the hosted ones.
dependency_overrides:
  maplibre_gl_platform_interface:
    path: ../maplibre_gl_platform_interface
  maplibre_gl_web:
    path: ../maplibre_gl_web
  maplibre_gl:
    path: ..

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/fill/cat_silhouette_pattern.png
    - assets/symbols/custom-icon.png
    - assets/symbols/2.0x/custom-icon.png
    - assets/symbols/3.0x/custom-icon.png
    - assets/symbols/custom-marker.png
    - assets/style.json
    - assets/osm_style.json
    - assets/sydney0.png
    - assets/sydney1.png