name: maplibre_gl_example
description: Demonstrates how to use the maplibre_gl plugin.
publish_to: 'none'
version: 1.0.0+1
repository: https://github.com/maplibre/flutter-maplibre-gl
issue_tracker: https://github.com/maplibre/flutter-maplibre-gl/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter

  maplibre_gl: ^0.19.0
  maplibre_gl_platform_interface: ^0.19.0
  location: ^5.0.3
  path_provider: ^2.0.15
  http: ^1.1.0
  collection: ^1.17.1
  # temporary fix:
  platform: ^3.1.0
  device_info_plus: ^9.0.2

dev_dependencies:
  flutter_lints: '>=3.0.0 <5.0.0'
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/fill/cat_silhouette_pattern.png
    - assets/symbols/custom-icon.png
    - assets/symbols/2.0x/custom-icon.png
    - assets/symbols/3.0x/custom-icon.png
    - assets/symbols/custom-marker.png
    - assets/style.json
    - assets/osm_style.json
    - assets/sydney0.png
    - assets/sydney1.png