name: maplibre_gl_web
description: Web platform implementation of maplibre_gl
version: 0.16.0
homepage: https://github.com/maplibre/flutter-maplibre-gl

flutter:
  plugin:
    platforms:
      web:
        pluginClass: MapboxMapPlugin
        fileName: mapbox_gl_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.3.0
  maplibre_gl_platform_interface:
    git:
      url: https://github.com/maplibre/flutter-maplibre-gl.git
      path: maplibre_gl_platform_interface
      ref: main
  maplibre_gl_dart:
    git:
      url: https://github.com/tappeddev/maplibre-gl-dart.git
      ref: 1d63c36e84f40ccaad4d9facc3b6c04809d56503 # fix-style-layers
  image: ^4.0.17


dependency_overrides:
  maplibre_gl_platform_interface:
    path: ../maplibre_gl_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"
