name: maplibre_gl_web
description: Web platform implementation of maplibre_gl. This package is only intended to be used by the maplibre_gl package.
version: 0.20.0
repository: https://github.com/maplibre/flutter-maplibre-gl
issue_tracker: https://github.com/maplibre/flutter-maplibre-gl/issues

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

flutter:
  plugin:
    platforms:
      web:
        pluginClass: MapLibreMapPlugin
        fileName: maplibre_gl_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  image: ^4.0.17
  js: ">=0.6.7 <0.8.0"
  maplibre_gl_platform_interface: ^0.20.0
  meta: ^1.3.0

dev_dependencies:
  very_good_analysis: ^5.0.0

platforms:
  web:
