name: maplibre_gl_web
description: Web platform implementation of maplibre_gl
version: 0.18.0
homepage: https://github.com/maplibre/flutter-maplibre-gl

flutter:
  plugin:
    implements: maplibre_gl
    platforms:
      web:
        pluginClass: MapLibreGlPlugin
        fileName: maplibre_gl_web.dart

dependencies:
  js: ^0.6.7
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.3.0
  maplibre_gl_platform_interface:
    git:
      url: https://github.com/maplibre/flutter-maplibre-gl.git
      path: maplibre_gl_platform_interface
      ref: main
  image: ^4.0.17

dependency_overrides:
  maplibre_gl_platform_interface:
    path: ../maplibre_gl_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"
