name: maplibre_gl_web
description: Web platform implementation of maplibre_gl
version: 0.15.1
homepage: https://github.com/m0nac0/flutter-maplibre-gl

flutter:
  plugin:
    platforms:
      web:
        pluginClass: MapboxMapPlugin
        fileName: mapbox_gl_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.3.0
  maplibre_gl_platform_interface:
    git:
      url: https://github.com/m0nac0/flutter-maplibre-gl.git
      path: maplibre_gl_platform_interface
      ref: main
  #mapbox_gl_dart: ^0.2.0-nullsafety
  mapbox_gl_dart:
    git:
      url: https://github.com/m0nac0/maplibre-gl-dart.git
      ref: main
  image: ^3.0.2

dependency_overrides:
  maplibre_gl_platform_interface:
    path: ../maplibre_gl_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"
