name: maplibre_gl
description: A Flutter plugin for integrating MapLibre Maps inside a Flutter application on Android, iOS and web platforms.
version: 0.25.0
repository: https://github.com/maplibre/flutter-maplibre-gl
issue_tracker: https://github.com/maplibre/flutter-maplibre-gl/issues
resolution: workspace

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  maplibre_gl_platform_interface: ^0.25.0
  maplibre_gl_web: ^0.25.0

dev_dependencies:
  very_good_analysis: ^10.0.0

flutter:
  plugin:
    platforms:
      android:
        package: org.maplibre.maplibregl
        pluginClass: MapLibreMapsPlugin
      ios:
        pluginClass: MapLibreMapsPlugin
      web:
        default_package: maplibre_gl_web

platforms:
  android:
  ios:
  web:
