name: maplibre_code_gen
description: code generation for flutter-maplibre-gl
publish_to: 'none'
resolution: workspace

version: 0.25.0

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  mustache_template: ^2.0.1
  recase: ^4.1.0

dev_dependencies:
  very_good_analysis: ^10.0.0