name: maplibre_gl_platform_interface
description: A common platform interface for the maplibre_gl plugin. This package is only intended to be used by the maplibre_gl package.
version: 0.20.0
repository: https://github.com/maplibre/flutter-maplibre-gl
issue_tracker: https://github.com/maplibre/flutter-maplibre-gl/issues

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.0.5

dev_dependencies:
  very_good_analysis: ^5.0.0
