name: Generate docs

on:
  push:
      branches: [ main ]

jobs:
  generate-docs:
    permissions: 
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2.10.0
        with:
          channel: 'stable'
          cache: true

      - name: Install dartdoc
        run: flutter pub global activate dartdoc
        
      - run: flutter pub get
      
      - name: Generate docs
        run: flutter pub global run dartdoc

      - name: Push docs
        run: |
          git config --global user.name "Docs Bot"
          git config --global user.email "docs-bot-flutter-maplibre-gl@localhost"
          git add -f doc
          git commit -m "docs: ${{ github.event.commits[0].id }}"
          git push --force origin main:docs
