name: Generate docs

on:
  push:
      branches: [ main ]

jobs:
  generate-docs:
    permissions: 
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2.3.0

      - name: Install dartdoc
        run: flutter pub global activate dartdoc
      
      - name: Generate docs
        run: flutter pub global run dartdoc

      - name: Push docs
        run: |
          git config --global user.name "Docs Bot"
          git config --global user.email "docs-bot-flutter-maplibre-gl@localhost"
          git add -f doc
          git commit -m "docs: ${{ github.event.commits[0].message }}"
          git push --force origin main:docs

